### ISSUE TITLE
v1.5.0 fails to compile on PlatformIO espressif32@6.13.0 (Arduino / ESP-IDF 4.4.7): missing spi_flash_mmap.h and esp_vfs_fat_spiflash_mount_rw_wl

### ISSUE THREAD

**Issue by paultanger** [QuickSpot/walter-arduino#142]
WalterModem v1.5.0 does not compile when using PlatformIO with `espressif32 @ 6.13.0`, which ships **Arduino v2.0.17 based on ESP-IDF 4.4.7**. Two IDF 5.x-only APIs are used unconditionally, with no `#if ESP_IDF_VERSION` guards.
 
This is related to #67 (`SPI_FLASH_SEC_SIZE` not declared) — both are symptoms of the same root cause: v1.5.0 assumes ESP-IDF 5.x but PlatformIO's Arduino framework still ships IDF 4.4.7.
 
## Environment
 
- **Platform:** `espressif32 @ 6.13.0` (Arduino v2.0.17, ESP-IDF 4.4.7, GCC 14.2.0)
- **Board:** DPTechnics Walter (ESP32-S3 N16R2)
- **Framework:** Arduino
- **WalterModem:** 1.5.0 (via `lib_deps = quickspot/WalterModem @ ^1.5.0`)
- **OS:** macOS (Apple Silicon), but the issue is platform-independent
 
### Error 1 — missing header
 
```
In file included from .pio/libdeps/walter/WalterModem/src/WalterModem.h:410,
fatal error: spi_flash_mmap.h: No such file or directory
```
 
`WalterModem.h` line 410 does `#include <spi_flash_mmap.h>` unconditionally (inside the `CONFIG_WALTER_MODEM_ENABLE_MOTA` block, which defaults to 1). This header was introduced in ESP-IDF 5.x when it was split out of `esp_spi_flash.h`. It does not exist in IDF 4.4.7.
 
### Error 2 — missing symbol
 
```
undefined reference to `esp_vfs_fat_spiflash_mount_rw_wl'
```
 
`WalterModem.cpp` lines 3769 and 3898 call `esp_vfs_fat_spiflash_mount_rw_wl()`. This is the ESP-IDF 5.x name. In IDF 4.4.7 the identical function exists under the old name `esp_vfs_fat_spiflash_mount()` (the `_rw_wl` suffix was added in IDF 5.0 to distinguish read-write wear-levelled mounts from read-only mounts; the old name was then deprecated).
 
## Workaround
 
A local shim header at `include/spi_flash_mmap.h` with `-I include` in `build_flags` resolves both issues without modifying the library:
 
```cpp
#ifndef SPI_FLASH_MMAP_H
#define SPI_FLASH_MMAP_H
 
#include <esp_partition.h>
#include <esp_vfs_fat.h>
 
#ifndef esp_vfs_fat_spiflash_mount_rw_wl
#define esp_vfs_fat_spiflash_mount_rw_wl esp_vfs_fat_spiflash_mount
#endif
 
#endif
```
 
Additionally, `build_unflags = -std=gnu++11` and `build_flags = -std=gnu++17` are required because the `CONFIG()` macro at `WalterModem.h` line 85 expands to `inline static constexpr` on the Arduino (non-KConfig) path, which is a C++17 feature.
 
## Suggested fix
 
Add ESP-IDF version guards in the library source:
 
**WalterModem.h** (around line 410):
```cpp
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
#include <spi_flash_mmap.h>
#else
#include <esp_spi_flash.h>
#endif
```
 
**WalterModem.cpp** (top of file or near the MOTA section):
```cpp
#if ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 0, 0)
#define esp_vfs_fat_spiflash_mount_rw_wl esp_vfs_fat_spiflash_mount
#define esp_vfs_fat_spiflash_unmount_rw_wl esp_vfs_fat_spiflash_unmount
#endif
```
 
This would restore compatibility with PlatformIO's Arduino framework (IDF 4.4.x) while keeping the IDF 5.x path working. The same approach could also fix #67's `SPI_FLASH_SEC_SIZE` issue.

**Comment by LeeNeu** [comment]
I ran into this same issue, but found a robust workaround using the **[pioarduino/platform-espressif32](https://github.com/pioarduino/platform-espressif32)** project.

This is a community-maintained fork of the standard PlatformIO `espressif32` platform. It provides significantly more up-to-date versions of the ESP-IDF (currently v5.5.4) and the Arduino core (v3.3.8).

### How to use this workaround
To switch, replace your existing `platform` key in your `platformio.ini` file with the following:

```ini
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
```
For more details, check out their [README.md](https://github.com/pioarduino/platform-espressif32/blob/main/README.md).

### Why this works
I have moved most of my Arduino-based projects to this platform. Beyond resolving build issues like this one, it offers:

Upstream IDF features: Access to newer Espressif features and hardware support.

Latest Arduino Core: Improved compatibility and stability provided by the updated ESP32 Arduino libraries.

This resolved the build issues for me immediately.
